### ISSUE TITLE
Breaks are never terminated.

### ISSUE THREAD

**Issue by ei14** [Bladtman242/potato#3]
Upon running `potato`, a 25 minute work session is initiated, and a tone is played upon completion. However, the program does nothing after this.

It is expected that after 5 minutes, the break would end, another tone would play, and another 25 minute work session would be initiated.

However, the program instead hangs indefinitely.

**Comment by Bladtman242** [comment]
This is intentional, though perhaps underdocumented
The intention is for the period to stop, but to hold off starting the next period until the user hits enter in the terminal.
The reason for this is that I often want to spend a few minutes finishing up when a period ends, but I don't want that time to cut into the next period.
This behaviour can be circumvented by passing the -s flag.

**Comment by Bladtman242** [comment]
I don't really use this behaviour any longer (I don't use potato much any longer), so feel free to make a pull request with different behaviour :)
